# This is a basic workflow to help you get started with Actions
"use client"

import { Canvas } from "@react-three/fiber"
import { OrbitControls, useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { useState, useRef } from "react"

// مكون زبون يحمل نموذج 3D
function CustomerModel({
  modelPath,
  initialPosition,
  scale = 1,
}: {
  modelPath: string
  initialPosition: [number, number, number]
  scale?: number
}) {
  const { scene } = useGLTF(modelPath)
  const meshRef = useRef<THREE.Group>(null)
  const [position, setPosition] = useState(new THREE.Vector3(...initialPosition))
  const [target, setTarget] = useState(
    new THREE.Vector3(
      Math.random() * 4 - 2,
      initialPosition[1],
      Math.random() * 4 - 2
    )
  )

  // حركة بسيطة للزبون: يمشي بين نقاط عشوائية
  useFrame(() => {
    if (!meshRef.current) return
    const dir = target.clone().sub(position)
    const dist = dir.length()
    if (dist < 0.05) {
      setTarget(
        new THREE.Vector3(
          Math.random() * 4 - 2,
          initialPosition[1],
          Math.random() * 4 - 2
        )
      )
    } else {
      dir.normalize()
      position.add(dir.multiplyScalar(0.01))
      setPosition(position.clone())
      meshRef.current.position.copy(position)
    }
  })

  return <primitive ref={meshRef} object={scene} scale={scale} position={position} />
}

// المشهد الرئيسي للعبة المقهى
export default function CafeScene() {
  return (
    <div className="w-full h-screen">
      <Canvas camera={{ position: [3, 3, 5], fov: 50 }}>
        <ambientLight intensity={0.5} />
        <directionalLight position={[5, 5, 5]} intensity={1} />
        <OrbitControls />

        {/* الأرضية */}
        <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.5, 0]}>
          <planeGeometry args={[20, 20]} />
          <meshStandardMaterial color="#c2b280" />
        </mesh>

        {/* الطاولة */}
        <mesh position={[0, 0, 0]}>
          <cylinderGeometry args={[0.5, 0.5, 0.1, 32]} />
          <meshStandardMaterial color="#8B4513" />
        </mesh>

        {/* كرسي */}
        <mesh position={[1, 0, 0]}>
          <boxGeometry args={[0.4, 0.4, 0.4]} />
          <meshStandardMaterial color="#a0522d" />
        </mesh>

        {/* الزبائن بنماذج 3D */}
        <CustomerModel modelPath="/models/old_man.glb" initialPosition={[1, 0, -1]} scale={1} />
        <CustomerModel modelPath="/models/young_man.glb" initialPosition={[-1, 0, 0]} scale={1} />
        <CustomerModel modelPath="/models/child.glb" initialPosition={[0, 0, 1]} scale={0.7} />
      </Canvas>
    </div>
  )
}
name: CI al

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
